[package]
name = "huffman-encoding"
version = "0.1.1"
license = "MIT/Apache-2.0"
description = "Huffman encoding of arbitrary data"
authors = ["conner bryan <conner@bryanthorpe.com>"]
edition = "2018"

[dependencies]
bit-vec = { version = "^0.6" }
thiserror = { version = "^1.0" }
